### ISSUE TITLE
Problems starting the project

### ISSUE THREAD

**Issue by albertozeni** [polomarcus/Spark-Structured-Streaming-Examples#7]
Hi, i have encountered problems when I want to run the project. I've downloaded all the packages (kafka and cassandra), adjusted the stackScripts accordingly, compiled the project (using sbt package), but when I do sbt run the project gives me the error in image and doesn't start. Can you give me some advice?
<img width="1280" alt="screenshot 2017-10-11 11 02 31" src="https://user-images.githubusercontent.com/22840782/31431341-b48237cc-ae73-11e7-87d1-5dc83a77bc12.png">

**Comment by polomarcus** [comment]
Thanks for submitting an issue. That's why we need to set up docker compose for this project and a CI service 😃 

This error doesn't ring any bells I am sorry, but I'll definitely going to check some potentiel environment issues.

Have you created the [3 Cassandra tables ](https://github.com/polomarcus/Spark-Structured-Streaming-Examples#cassandra-table) using csql?

**Comment by albertozeni** [comment]
No I didn't, and I didn't set the kafka topic neither, can you please guide me into a complete installation?

**Comment by polomarcus** [comment]
All you should know *should* be here : https://github.com/polomarcus/Spark-Structured-Streaming-Examples#requirements

To create the kafka topic "test" : https://github.com/polomarcus/Spark-Structured-Streaming-Examples/blob/master/stackScripts/startKafkaStack.sh#L8

To be sure that you Kafka is well setup, after launching a console consumer, send a message using [this command](https://github.com/polomarcus/Spark-Structured-Streaming-Examples#send-a-message)

For Cassandra you need to install [cqlsh](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/cqlsh.html)

**Comment by polomarcus** [comment]
@albertozeni all good installing and running Kafka and Cassandra?

**Comment by albertozeni** [comment]
No sorry, I tried many times and I couldn't get it started, I switched to another project since I just wanted to use this as an example for spark streaming.

**Comment by polomarcus** [comment]
hi @albertozeni 

To let you know, I've recently merged a PR for using docker-compose, it should be easier to start the project : `./start-docker-compose.sh`

I've updated the README as well

**Comment by callamd** [comment]
Is spark supposed to be running locally?
